---
abstract: 'Everything useful when developing Map::Metro maps'
author:
  - 'Erik Carlsson <info@code301.com>'
build_requires: {}
configure_requires:
  Module::Build::Tiny: '0.039'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.029, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Task-MapMetro-Dev
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Dist::Zilla: '5.000'
  Dist::Zilla::MintingProfile::MapMetro::Map: '0.1200'
  Dist::Zilla::Plugin::MapMetro::MakeGraphViz: '0.1100'
  GraphViz2: '2.20'
  Map::Metro: '0.2002'
resources:
  bugtracker: https://github.com/Csson/p5-Task-MapMetro-Dev/issues
  homepage: https://github.com/Csson/p5-Task-MapMetro-Dev
  repository: https://github.com/Csson/p5-Task-MapMetro-Dev.git
version: '0.1000'
